name: Node.js CI
on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [ '12' ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run electron:build
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: buildfile
          path: dist_electron

